# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.cache/wt [current_project]
set_property parent.project_path C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Address_Creator.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Controller.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Deserializer.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/MemInterpreter.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Segment_LED_Interface.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Serializer.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/Timer.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/scaledclock.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/synchronizer.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/twoinputmux.sv}
  {C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/TopModule.sv}
}
read_ip -quiet C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/teamproject/teamproject.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/jarodr30/Desktop/CSE320-Project-Files-master/source files/constraints.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TopModule -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TopModule.dcp

catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
